### ISSUE TITLE
ObservableHQ issue

### ISSUE THREAD

**Issue by ctzurcanu** [web-eid/web-eid.js#37]
Tried to use this in Observable https://observablehq.com/ :

```
webeid = require('web-eid/web-eid.js')
webeid.getVersion()
```
Error: App has disappeared

seemingly the VERSION is: "0.0.5"

**Comment by ctzurcanu** [comment]
same error in React:

web-eid.js:61 Uncaught (in promise) Error: App has disappeared
    at web-eid.js:61:1
    at new Promise (<anonymous>)
    at msg2promise (web-eid.js:56:1)
    at fields.getVersion (web-eid.js:83:1)
    at Module.<anonymous> (index.js:11:1)
    at ./src/index.js (index.js:17:1)
    at __webpack_require__ (bootstrap:851:1)
    at fn (bootstrap:150:1)
    at 1 (index.js:17:1)
    at __webpack_require__ (bootstrap:851:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:81

**Comment by mrts** [comment]
Hi, @ctzurcanu!

This is the old version published in NPM by previous project. We just recently got rights for NPM and will publish a new version there when we are ready for this.

Meanwhile please use the GitLab Package Registry as [written in the docs](https://github.com/web-eid/web-eid.js#1-add-web-eidjs-to-the-project) to install the latest official version:

```sh
echo @web-eid:registry=https://gitlab.com/api/v4/packages/npm >> .npmrc
npm install @web-eid/web-eid-library
```

**Comment by ctzurcanu** [comment]
unfortunately, that is not an option. In that context:
require('web-eid/web-eid.js') // works
require('@web-eid/web-eid-library') // does not work

https://observablehq.com/@observablehq/module-require-debugger offers no solutions for importing @web-eid/web-eid-library

Is there a file that can be included by <script src="file.js"> for ver. 2?

**Comment by mrts** [comment]
Sure, you can include _web-eid.js_ directly. Each release contains a pre-built ZIP with ES module, IIFE and UMD builds, see https://github.com/web-eid/web-eid.js/releases/tag/v2.0.1:
![image](https://user-images.githubusercontent.com/44880/212415654-e7a11de7-da79-4dc1-b44d-0de81e67e99b.png)
