### ISSUE TITLE
Error in Jest test

### ISSUE THREAD

**Issue by tab** [web-eid/web-eid.js#43]
I am encountering an error in my Jest test for a specific component. 
The component works correctly when rendered in the browser, but the test fails with an error. 

Here is the code for the component:

```
import React, { ComponentType, useEffect, useState } from "react"
import { compose } from "@reduxjs/toolkit"
...
import { authenticate } from "@web-eid/web-eid-library/web-eid"

...

const IdCard = () => {
  ...

  const handleSubmit = async () => {
    try {
      const payload = await authenticate(nonce, { lang: "en" })
      
      ...
    } catch (error) {
      ...
    }
  }
}

export default compose<ComponentType>()(IdCard)
```

And here is the relevant test code:

```
import React from "react"
import { waitFor } from "@testing-library/react"
import "@testing-library/jest-dom"

import { renderWithProvider } from "__tests__/support/redux/renderWith"
import { IdCard } from "pages/sessions"

describe("IdCard", () => {
  test("it renders page", async () => {
    const title = "Sign in to your account"
    const { asFragment, getByText, getByTestId } = renderWithProvider(
      <IdCard />,
    )

    await waitFor(() => getByTestId("login-id-card-page"))
    expect(asFragment()).toMatchSnapshot()
    expect(getByText(title)).toBeInTheDocument()
  })
})
```

Error Message:

```
 FAIL  src/__tests__/pages/sessions/login/index.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /usr/src/app/node_modules/@web-eid/web-eid-library/web-eid.js:22
    import Action from "./models/Action";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import { useNavigate } from "react-router-dom"
      5 | import { FormikHelpers as FormikActions } from "formik"
    > 6 | import { authenticate } from "@web-eid/web-eid-library/web-eid"
        | ^
...
```

Thank you for your assistance in resolving this issue.

**Comment by tab** [comment]
The same result with different import

```
import * as WebEID from "@web-eid/web-eid-library/dist/es/web-eid"
...

  const handleSubmit = async () => {
    try {
      const payload = await WebEID.authenticate(nonce, { lang: "en" })
      
      ...
    } catch (error) {
      ...
    }
  }
```

**Comment by tab** [comment]
I made a demo with Create React App
https://github.com/tab/web-eid-react-demo

```
docker-compose build
docker-compose up

docker-compose exec web-eid-demo sh

yarn run test
```

Got the same problem

```
 FAIL  src/IdCard.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /usr/src/app/node_modules/@web-eid/web-eid-library/web-eid.js:22
    import Action from "./models/Action";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { useEffect, useState } from "react"
    > 2 | import { authenticate } from "@web-eid/web-eid-library/web-eid"
        | ^
      3 |
      4 | const IdCard = () => {
      5 |   const [nonce, setNonce] = useState("")

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/IdCard.tsx:2:1)

 FAIL  src/App.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /usr/src/app/node_modules/@web-eid/web-eid-library/web-eid.js:22
    import Action from "./models/Action";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import React, { useEffect, useState } from "react"
    > 2 | import { authenticate } from "@web-eid/web-eid-library/web-eid"
        | ^
      3 |
      4 | const IdCard = () => {
      5 |   const [nonce, setNonce] = useState("")

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/IdCard.tsx:2:1)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        5.423 s
Ran all test suites.

Watch Usage
 › Press f to run only failed tests.
 › Press o to only run tests related to changed files.
 › Press q to quit watch mode.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press Enter to trigger a test run.

```

Additional logs

```
 ⠿ Container web-eid-react-demo-web-eid-demo-1  Created                                                            0.0s
Attaching to web-eid-react-demo-web-eid-demo-1
web-eid-react-demo-web-eid-demo-1  | yarn run v1.22.19
web-eid-react-demo-web-eid-demo-1  | $ react-scripts start
web-eid-react-demo-web-eid-demo-1  | (node:35) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
web-eid-react-demo-web-eid-demo-1  | (Use `node --trace-deprecation ...` to show where the warning was created)
web-eid-react-demo-web-eid-demo-1  | (node:35) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
web-eid-react-demo-web-eid-demo-1  | Starting the development server...
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Compiled with warnings.
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/config.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/config.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ActionPendingError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ActionPendingError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ActionTimeoutError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ActionTimeoutError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ContextInsecureError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ContextInsecureError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ErrorCode.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ErrorCode.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ExtensionUnavailableError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ExtensionUnavailableError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/MissingParameterError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/MissingParameterError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/NativeFatalError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/NativeFatalError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/NativeInvalidArgumentError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/NativeInvalidArgumentError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/NativeUnavailableError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/NativeUnavailableError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/UnknownError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/UnknownError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/UserCancelledError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/UserCancelledError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/UserTimeoutError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/UserTimeoutError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/VersionInvalidError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/VersionInvalidError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/VersionMismatchError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/VersionMismatchError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/models/Action.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/models/Action.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/services/WebExtensionService.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/services/WebExtensionService.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/utils/errorSerializer.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/utils/errorSerializer.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/utils/sleep.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/utils/sleep.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/web-eid.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/web-eid.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | Search for the keywords to learn more about each warning.
web-eid-react-demo-web-eid-demo-1  | To ignore, add // eslint-disable-next-line to the line before.
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/config.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/config.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/config.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/ActionPendingError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ActionPendingError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ActionPendingError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/ActionTimeoutError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ActionTimeoutError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ActionTimeoutError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/ContextInsecureError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ContextInsecureError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ContextInsecureError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/ErrorCode.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ErrorCode.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ErrorCode.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/ExtensionUnavailableError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/ExtensionUnavailableError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/ExtensionUnavailableError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/MissingParameterError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/MissingParameterError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/MissingParameterError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/NativeFatalError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/NativeFatalError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/NativeFatalError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/NativeInvalidArgumentError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/NativeInvalidArgumentError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/NativeInvalidArgumentError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/NativeUnavailableError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/NativeUnavailableError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/NativeUnavailableError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/UnknownError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/UnknownError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/UnknownError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/UserCancelledError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/UserCancelledError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/UserCancelledError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/UserTimeoutError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/UserTimeoutError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/UserTimeoutError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/VersionInvalidError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/VersionInvalidError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/VersionInvalidError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/errors/VersionMismatchError.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/errors/VersionMismatchError.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/errors/VersionMismatchError.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/models/Action.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/models/Action.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/models/Action.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/services/WebExtensionService.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/services/WebExtensionService.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/services/WebExtensionService.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/utils/errorSerializer.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/utils/errorSerializer.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/utils/errorSerializer.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/utils/sleep.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/utils/sleep.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/utils/sleep.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | WARNING in ./node_modules/@web-eid/web-eid-library/web-eid.js
web-eid-react-demo-web-eid-demo-1  | Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
web-eid-react-demo-web-eid-demo-1  | Failed to parse source map from '/usr/src/app/node_modules/src/web-eid.ts' file: Error: ENOENT: no such file or directory, open '/usr/src/app/node_modules/src/web-eid.ts'
web-eid-react-demo-web-eid-demo-1  |
web-eid-react-demo-web-eid-demo-1  | webpack compiled with 20 warnings
web-eid-react-demo-web-eid-demo-1  | No issues found.

```

**Comment by tab** [comment]
Issue was fixed with

```
"jest": {
    "transformIgnorePatterns": ["node_modules/(?!@web-eid/)"]
},
```

**Comment by mrts** [comment]
Good to hear there is a workaround, thanks for letting us know! Closing for now.
